// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":true,"description":"メニュー画面のレイアウトを変更します。","parameters":{}},
{"name":"CommandEquip","status":true,"description":"Equip Battle Command v1.1.1","parameters":{"Unchangeable Types":""}},
{"name":"BattleGrow","status":true,"description":"戦闘の行動に応じた成長をするシステムを提供","parameters":{}},
{"name":"Hit","status":true,"description":"戦闘での物理攻撃の命中演算を変更","parameters":{}},
{"name":"MaxDamage","status":true,"description":"戦闘での物理攻撃の命中演算を変更","parameters":{}}
];
